server:
  port: 8761


management:  endpoints:    web:      exposure:        include: '*'
        
eureka:  client:
    service-url:      defaultZone: http://localhost:8761/eureka    fetch-registry: false
    register-with-eureka: false
